### ISSUE TITLE
Bug in the docs' Accessing-CMIP6-data-on-GCS example

### ISSUE THREAD

**Issue by briochemc** [meggart/Zarr.jl#53]
The [Accessing-CMIP6-data-on-GCS example](https://meggart.github.io/Zarr.jl/latest/s3examples/#Accessing-CMIP6-data-on-GCS-1) throws for me because

```julia
cmip6_base["cmip6-zarr-consolidated-stores.csv"]
```

is empty (a `nothing` to be specific) and so `IOBuffer` throws that it does not have a method for `::Nothing`. 

(Julia Version 1.5.3, Zarr v0.4.6)

**Comment by gaelforget** [comment]
I think that this error message resulted from commit 

https://github.com/meggart/Zarr.jl/pull/41/commits/86a86ea2531a78a431fd1d27e337eeb354d1c00a

FYI, on v1.5, if I revert that commit then I get a step further but to another error (which had to do with being neither a `ZArray` nor a `ZGroup` if I recall correctly)

**Comment by meggart** [comment]
I forgot to mention it here, but I think this got fixed in #55 . Forgot to cross-post this here. For me the example works on Zarr v0.6, could you try?

**Comment by briochemc** [comment]
I just tried it (until the Minio.jl part) and it worked without throwing for me! 😃

**Comment by gaelforget** [comment]
> I just tried it (until the Minio.jl part) and it worked without throwing for me! 😃

Same here. Thanks @meggart
