### ISSUE TITLE
support time data types

### ISSUE THREAD

**Issue by lazarusA** [meggart/Zarr.jl#56]
By trying to open a .zarr file I encounter the following error.

```
using Zarr
file = zopen("filename.zarr") 
```

ArgumentError: <M8[D] is not a valid numpy typestr Stacktrace: [1] typestr(s::String, filterlist::Nothing) @ Zarr ~/.julia/packages/Zarr/EjE1w/src/metadata.jl:55 [2] Zarr.Metadata(d::Dict{String, Any}) @ Zarr ~/.julia/packages/Zarr/EjE1w/src/metadata.jl:142 [3] Zarr.Metadata(s::String) @ Zarr ~/.julia/packages/Zarr/EjE1w/src/metadata.jl:131 [4] getmetadata(s::DirectoryStore) @ Zarr ~/.julia/packages/Zarr/EjE1w/src/Storage/Storage.jl:100 [5] ZArray(s::DirectoryStore, mode::String) @ Zarr ~/.julia/packages/Zarr/EjE1w/src/ZArray.jl:95 [6] zopen(s::DirectoryStore, mode::String; consolidated::Bool) @ Zarr ~/.julia/packages/Zarr/EjE1w/src/ZGroup.jl:62 [7] zopen(s::DirectoryStore, mode::String) @ Zarr ~/.julia/packages/Zarr/EjE1w/src/ZGroup.jl:60 [8] ZGroup(s::DirectoryStore, mode::String) @ Zarr ~/.julia/packages/Zarr/EjE1w/src/ZGroup.jl:18 [9] zopen(s::DirectoryStore, mode::String; consolidated::Bool) @ Zarr ~/.julia/packages/Zarr/EjE1w/src/ZGroup.jl:64 [10] zopen(s::DirectoryStore, mode::String) @ Zarr ~/.julia/packages/Zarr/EjE1w/src/ZGroup.jl:60 [11] #zopen#75 @ ~/.julia/packages/Zarr/EjE1w/src/ZGroup.jl:77 [inlined] [12] zopen (repeats 2 times) @ ~/.julia/packages/Zarr/EjE1w/src/ZGroup.jl:77 [inlined] [13] top-level scope @ In[19]:2 [14] eval @ ./boot.jl:360 [inlined] [15] include_string(mapexpr::typeof(REPL.softscope), mod::Module, code::String, filename::String) @ Base ./loading.jl:1094

**Comment by visr** [comment]
`<M8[D]` means the data is a (little endian) date stored in 8 bytes, with daily units. Time types are not yet supported, though this would be nice to have.

See also the reference here: https://zarr.readthedocs.io/en/stable/spec/v2.html#data-type-encoding. This is encoded in [metadata.jl](https://github.com/meggart/Zarr.jl/blob/d81cffa2a4c7fdfb10a69d88a0d01c2c52c019a2/src/metadata.jl).

We should verify, but `<M8[D]` could probably be captured into a `Date`. Although the binary representation / epoch doesn't seem to be equal, so probably it needs to be mapped a bit differently.

```python
import numpy as np
t = np.datetime64("2021-04-16", "D")
t.astype(np.int64)  # -> 18733
```

```julia
using Dates
t = Date("2021-04-16")
Dates.value(t)  # -> 737896
```

**Comment by meggart** [comment]
I just created a branch, see #57
