### ISSUE TITLE
Parallel reads are slow

### ISSUE THREAD

**Issue by tbenst** [meggart/Zarr.jl#64]
Hello, thanks for this package! I'm exploring switching to Zarr.jl from HDF5.jl, but I'm having trouble with performance, so wanted to check if I'm missing something, or if this should be a feature enhancement request. At the moment, multithreading seems to be slower than single-threading in Zarr.jl, and HDF5.jl is ~3x faster for multiprocessing.

```julia
using Zarr, HDF5, BenchmarkTools, Distributed
import Base.Threads: @threads

addprocs(36)
@everywhere using HDF5, Zarr

path = joinpath(mktempdir(), "test.zarr")
M, N = 1000, 10000
z1 = zcreate(Float32, M,N,path = path,chunks=(M/10, N/10))
m1 = rand(Float32, M,N);
z1[:,:] .= m1
h5_path = joinpath(mktempdir(), "test.h5")
h5 = h5open(h5_path, "w")
h5["a"] = m1;
close(h5)
h5 = h5open(h5_path, "r"; swmr=true)

function threads_sum(arr)
    result = zeros(size(arr,1))

    @threads for i = 1:size(arr,1)
        result[i] = sum(arr[i,:])
    end
    result
end

@everywhere function distributed_sum(arr::HDF5.File; dset="a")
    @distributed vcat for i = 1:size(arr[dset],1)
        h5 = h5open(arr.filename)
        array = h5[dset]
        sum(array[i,:])
        close(h5)
    end
end

@everywhere function distributed_sum(arr::ZArray)
    @distributed vcat for i = 1:size(arr,1)
        sum(arr[i,:])
    end
end

function seq_sum(arr)
    result = zeros(size(arr,1))

    for i = 1:size(arr,1)
        result[i] = sum(arr[i,:])
    end
    result
end
##
@btime seq_sum(m1); # 44ms
@btime threads_sum(m1); # 3ms
##
@btime seq_sum(h5["a"]); # 4.37s
@btime seq_sum(z1); # 2.08s
@btime threads_sum(z1); # 3.36s
@btime distributed_sum(h5) # 194ms
@btime distributed_sum(z1) # 590ms
```

**Comment by meggart** [comment]
I can not really reproduce your benchmarks. How many cores does your machine have. I just tried on a server with 120 cores and got the following results:

````julia
@btime seq_sum(m1); # 19ms
@btime threads_sum(m1); # 0.7ms
@btime seq_sum(h5["a"]); # 4.1s
@btime seq_sum(z1); # 2.08s
@btime threads_sum(z1); # 1.22s
@btime distributed_sum(h5); # 226.95ms
@btime distributed_sum(z1); # 165.779ms
````

Note that by default compression is enabled, so in your example we are really looking at a compute-bound problem, not an IO-bound one. If you want to test without compression, to only test pure IO, just set `compressor=NoCompressor()` as a keyword argument to zcreate.

Also, the way you are accessing your array is not really chunk-efficient. Your chunk blocks are of size (M/10 x N/10) but your are accessing the data row-wise. If you want to access the data in a chunk-natural way, you could simply use `sum(z1,dims=2)` which accesses the chunks in a sequential way.  If you are free to chunk your input array the way you want, it would of course be most efficient to use `chunks=(1,N)`. 

So if I disable compression and reset the chunk size, I get the following timings:

````julia
z1 = zcreate(Float32, M,N,path = path,chunks=(M/10, N/10), compressor=Zarr.NoCompressor())
@btime seq_sum(z1); # 53ms
@btime threads_sum(z1); # 2.2ms
@btime distributed_sum(z1); # 3.315ms
````

**Comment by tbenst** [comment]
I'm on an Intel Core i9-10980XE CPU (18 cores / 36 threads). And thank you! `NoCompressor` fixed the speed discrepancy--I hadn't realized I was making an unfair comparison.

```
@btime seq_sum(h5["a"]); # 4.67s
@btime seq_sum(z1); # 1.56s
@btime threads_sum(z1); # 336ms
@btime distributed_sum(h5) # 280ms
@btime distributed_sum(z1) # 307ms
```

Is it surprising that with compression there is such a big speed difference in Zarr for threads vs distributed? Perhaps a BLOSC library limitation?
