### ISSUE TITLE
How to create string array?

### ISSUE THREAD

**Issue by tbenst** [meggart/Zarr.jl#74]
Thanks so much for this awesome package! Just wondering if possible to do the equivalent of https://zarr.readthedocs.io/en/stable/tutorial.html#string-arrays, namely (in python): `z = zarr.zeros(10, dtype='S6')` I wasn't sure if there was an appropriate type to use for ASCII / 8-bit character data.

**Comment by meggart** [comment]
Data encoded with "S6" are interpreted as `MaxLengthString`s. To create such an array you can do:

````julia
julia> using Zarr

julia> using Zarr.MaxLengthStrings: MaxLengthString

julia> z = zcreate(MaxLengthString{6,UInt8}, 3, 3)
ZArray{MaxLengthString{6, UInt8}} of size 3 x 3

julia> z[:,:] .= "hello"
Disk Array with size 3 x 3

julia> z[:,:]
3×3 Matrix{MaxLengthString{6, UInt8}}:
 "hello"  "hello"  "hello"
 "hello"  "hello"  "hello"
 "hello"  "hello"  "hello"
````

You can checkout the implementation of `MaxLengthString`s here:

https://github.com/meggart/Zarr.jl/blob/d81cffa2a4c7fdfb10a69d88a0d01c2c52c019a2/src/MaxLengthStrings.jl

**Comment by tbenst** [comment]
Excellent; thank you!
